import pathlib

class String_Handler:
    _instance = None
    _auto_counter = 1

    def __init__(self, lang_folder="lang"):
        self.lang_folder = pathlib.Path(lang_folder)
        self.file_path = self.lang_folder / "english.lng"
        self.first_run()

    @classmethod
    def get_instance(self, lang_folder=None):
        if self._instance is None:
            self._instance = self(lang_folder or "lang")
        return self._instance

    def write_string(self, text: str, str_name: str = None) -> str:
        """
        Writes a string to the language file.
        If str_name is provided: prepends 'str_' if needed and uses that name.
        If str_name is None: automatically generates 'autostr_X' incremental names.
        Returns the name wrapped in string(...).
        """
        self.lang_folder.mkdir(parents=True, exist_ok=True)

        # Determine the string name
        if str_name is None:
            str_name = f"autostr_{self._auto_counter}"
            self._auto_counter += 1
        else:
            # Remove some illegal characters from string
            str_name = self.clean_string(str_name)
            str_name = str_name.lower()
            # Prepend 'str_' if not already present
            if not str_name.startswith("str_"):
                str_name = f"str_{str_name}"

        # Append to file
        with open(self.file_path, "a", encoding="utf-8") as f:
            f.write(f"{str_name:<40}:{text}\n")

        return f"string({str_name})"

    def first_run(self):
        # Ensure folder exists
        self.lang_folder.mkdir(parents=True, exist_ok=True)

        # Overwrite file and write header
        with open(self.file_path, "w", encoding="utf-8") as f:
            f.write("##grflangid 0x01\n")
            f.write("# AUTOGENERATED FILE, DO NOT MODIFY THIS FILE DIRECTLY, IT WILL BE OVERWRITTEN\n\n")

            # Load manual strings
            yaml_path = self.lang_folder / "manual_strings.yaml"
            if yaml_path.exists():
                with open(yaml_path, "r", encoding="utf-8") as yf:
                    for line in yf:
                        line = line.strip()
                        if not line or ":" not in line:
                            continue
                        key, value = line.split(":", 1)
                        key = key.strip()
                        value = value.lstrip()  # strip only leading spaces
                        f.write(f"{key}:{value}\n")

        self._first_run_done = True

    def clean_string(self, in_str):
        illegal_name_chars = "(),"
        out_str = in_str.translate(str.maketrans("", "", illegal_name_chars))
        return str(out_str)

# Define nml_str as a global shortcut
nml_str = String_Handler.get_instance().write_string
# Define clean_str as a global shortcut
clean_str = String_Handler.get_instance().clean_string