import logging
from Badge import BadgeRegistry
from .NmlBadgeWriter import NmlBadgeWriter

logger = logging.getLogger(__name__)


class NmlCollator:
    def __init__(self):
        pass

    def collate(self, files, project_name):
        self.output_file = f"Build/{project_name}.nml"

        with open(self.output_file, "w", encoding="utf-8") as f:
            f.write("// !!!!! Warning, auto generated file. Do not edit this file. !!!!!\n")
            f.write("// This .nml file is auto-generated from the individual .gnml files for each variant and the GRF.\n")
            f.write("// Do not edit this file, it will be over-written during the next build.\n")

            # Split GRF header from vehicle variant files
            grf_files = [file for file in files if "GRF.gnml" in str(file)]
            other_files = [file for file in files if "GRF.gnml" not in str(file)]

            # 1. Collated GRF block
            for file in grf_files:
                logger.debug(f"Collating GRF file: {file}")
                with open(file, "r", encoding="utf-8") as infile:
                    f.write(f"\n\n// File: {file}\n")
                    f.write(infile.read())

            # 2. Write badgetable and FEAT_BADGES item definitions
            NmlBadgeWriter().write_all(f)

            # 3. Collated vehicle item files
            for file in other_files:
                logger.debug(f"Collating variant file: {file}")
                with open(file, "r", encoding="utf-8") as infile:
                    f.write(f"\n\n// File: {file}\n")
                    f.write(infile.read())

        logger.info(f"Collated NML written to {self.output_file}")
        return self.output_file