import logging
import re
import shutil
from pathlib import Path

from Badge import BadgeRegistry
from .NmlBadgeWriter import NmlBadgeWriter

logger = logging.getLogger(__name__)


class NmlCollator:
    def __init__(self):
        pass

    def collate(
        self,
        files,
        project_name,
        custom_nml_folder=None,
        project_path=None,
        candidates_root=None,
        staged_candidate_nml=None,
        vehicle_nml_files=None,
        variant_owners=None,
        generated_trailing_nml=None,
        skip_custom_nml=None,
    ):
        """Collate every NML block into one file.

        Order: the GRF header and project-level custom NML first (they are GRF-scoped),
        then the badge table, then each vehicle's own `.pnml` immediately before that
        vehicle's generated blocks, then GRF-level blocks the caller generated once the
        items existed (a purchase-list `sort` block names item symbols), then any
        `custom_nml/append` files.

        Vehicle NML is deliberately *not* hoisted to the top: a switch costs a concurrent
        spritegroup slot while it is in scope, and OpenTTD only allows 255 of those, so
        each vehicle's hand-written chain is kept adjacent to the item that uses it.
        """
        project_root = Path(project_path).expanduser().resolve() if project_path else Path.cwd()
        self.output_file = str(project_root / "Build" / f"{project_name}.nml")
        custom_nml_output = project_root / "WorkingData" / project_name / "custom_nml"
        Path(self.output_file).parent.mkdir(parents=True, exist_ok=True)
        custom_nml_files = []
        trailing_nml_files = []
        skipped = {Path(path).expanduser().resolve() for path in (skip_custom_nml or [])}

        if custom_nml_folder:
            custom_nml_source = Path(custom_nml_folder)
            if custom_nml_source.is_dir():
                for source_file in sorted(path for path in custom_nml_source.rglob("*") if path.is_file()):
                    relative_path = source_file.relative_to(custom_nml_source)
                    destination_file = custom_nml_output / relative_path
                    destination_file.parent.mkdir(parents=True, exist_ok=True)
                    self._copy_custom_nml_file(source_file, destination_file, project_path)
                    # A GRF may name a file under custom_nml/append as its manual
                    # purchase list. The builder also supplies that file's contents as
                    # a generated trailing block, so it is written once, from the
                    # generated copy, and skipped here.
                    if source_file.resolve() in skipped:
                        logger.debug(f"Skipping custom NML file named by the GRF: {source_file}")
                        continue
                    if relative_path.parts and relative_path.parts[0] == "append":
                        trailing_nml_files.append(destination_file)
                    else:
                        custom_nml_files.append(destination_file)
                logger.info(
                    f"Copied {len(custom_nml_files) + len(trailing_nml_files)} custom NML file(s) "
                    f"to {custom_nml_output}"
                )
            else:
                logger.debug(f"No custom NML folder found at '{custom_nml_source}'.")

        input_files = [str(Path(file).resolve()) for file in files]
        custom_paths = [str(Path(path).resolve()) for path in custom_nml_files]
        candidate_paths = self._candidate_folders(candidates_root)
        staged_root = Path(staged_candidate_nml).resolve() if staged_candidate_nml else None

        # Any candidate-adjacent NML that the caller did not map to a vehicle is still
        # treated as supplied rather than as a generated variant block.
        unmapped_candidate_nml = [
            file
            for file in input_files
            if "GRF.gnml" not in file
            and Path(file).parent in candidate_paths
            and (staged_root is None or Path(file).parent != staged_root)
        ]

        per_vehicle = {
            str(key): [str(Path(path).resolve()) for path in paths]
            for key, paths in (vehicle_nml_files or {}).items()
        }

        template_container = [file for file in input_files if "Templates.gnml" in file][:1]
        template_sources = [] if template_container else self._template_sources(input_files)
        grf_level = (
            [file for file in input_files if "GRF.gnml" in file]
            + template_container
            + template_sources
            + custom_paths
            + unmapped_candidate_nml
        )

        variant_files = [
            file
            for file in input_files
            if "GRF.gnml" not in file and file not in grf_level
        ]

        with open(self.output_file, "w", encoding="utf-8") as f:
            f.write("// !!!!! Warning, auto generated file. Do not edit this file. !!!!!\n")
            f.write("// This .nml file is auto-generated from the individual .gnml files for each variant and the GRF.\n")
            f.write("// Do not edit this file, it will be over-written during the next build.\n")

            # 1. GRF-scoped blocks: the GRF header, the template definitions, any
            #    project-level custom NML, and candidate NML the caller did not map.
            for file in grf_level:
                logger.debug(f"Collating GRF-level NML file: {file}")
                with open(file, "r", encoding="utf-8") as infile:
                    f.write(f"\n\n// File: {file}\n")
                    f.write(infile.read())

            # 2. Write badgetable and FEAT_BADGES item definitions
            NmlBadgeWriter().write_all(f)

            # 3. Each vehicle's own NML, immediately before its generated blocks.
            written_vehicle_nml: set[str] = set()
            owners = {str(Path(path).resolve()): owner for path, owner in (variant_owners or {}).items()}
            for file in variant_files:
                owner = owners.get(file)
                if owner is not None:
                    for pnml in per_vehicle.get(str(owner), []):
                        if pnml in written_vehicle_nml:
                            continue
                        logger.debug(f"Collating vehicle NML file: {pnml}")
                        with open(pnml, "r", encoding="utf-8") as infile:
                            f.write(f"\n\n// File: {pnml}\n")
                            f.write(infile.read())
                        written_vehicle_nml.add(pnml)

                logger.debug(f"Collating variant file: {file}")
                with open(file, "r", encoding="utf-8") as infile:
                    f.write(f"\n\n// File: {file}\n")
                    f.write(infile.read())

            # 4. GRF-level NML the builder generated after the items existed.
            for text in (generated_trailing_nml or []):
                banner = self._generated_banner(text)
                logger.debug(f"Collating generated trailing NML block: {banner}")
                f.write(f"\n\n// File: generated/{banner}\n")
                f.write(text.rstrip("\n") + "\n")

            # 5. Files under custom_nml/append are deliberately last, so a project can
            # still add a GRF-level declaration after everything generated.
            for file in trailing_nml_files:
                logger.debug(f"Collating trailing custom NML file: {file}")
                with open(file, "r", encoding="utf-8") as infile:
                    f.write(f"\n\n// File: {file}\n")
                    f.write(infile.read())

        logger.info(f"Collated NML written to {self.output_file}")
        return self.output_file

    @staticmethod
    def _generated_banner(text: str) -> str:
        """Name a generated trailing block after the feature it sorts."""
        match = re.search(r"sort\(\s*([A-Z_]+)", text)
        return f"purchase_list_{match.group(1).lower()}.pnml" if match else "generated.pnml"

    @staticmethod
    def _template_sources(input_files) -> list:
        """The template `.pnml` files BRBuild pre-wrote into this project's NML list.

        Only needed when `Templates.gnml` is absent; when it is present these files are
        already inlined in it.
        """
        return [
            file
            for file in input_files
            if "GRF.gnml" not in file
            and "Templates.gnml" not in file
            and Path(file).parent.name.lower() == "templates"
        ]

    @staticmethod
    def _candidate_folders(candidates_root) -> set:
        """Folders inside the project that hold a vehicle candidate's own NML.

        A candidate is identified by a folder holding a YAML file with the folder's own
        name, matching `Builder/CandidateFinder`, so the collator can recognise supplied
        NML without being told which file belongs to which candidate.
        """
        if candidates_root is None:
            return set()

        root = Path(candidates_root)
        if not root.is_dir():
            return set()

        folders = set()
        for folder in root.rglob("*"):
            if not folder.is_dir():
                continue
            if folder.name in {"new", "ingested", "error", "original"}:
                continue
            if (folder / f"{folder.name}.yaml").is_file():
                folders.add(folder.resolve())
        return folders

    def copy_supplied_nml(self, source_file, destination_file, project_path=None) -> str:
        """Copy hand-written NML into the working folder, making its paths absolute.

        Relative quoted paths inside the file are resolved against the source's own
        folder first, then the project root, so a candidate's `.pnml` can address its
        images the way the artist wrote them.
        """
        destination_file = Path(destination_file)
        destination_file.parent.mkdir(parents=True, exist_ok=True)
        self._copy_custom_nml_file(Path(source_file), destination_file, project_path)
        return str(destination_file)

    def _copy_custom_nml_file(self, source_file, destination_file, project_path):
        shutil.copy2(source_file, destination_file)
        if source_file.suffix.lower() not in {".nml", ".pnml", ".gnml"} or project_path is None:
            return

        content = source_file.read_text(encoding="utf-8")
        path_pattern = re.compile(r"([\"'])([^\"'\n]+)\1")

        def make_absolute(match):
            raw_path = match.group(2)
            path = Path(raw_path)
            if path.is_absolute():
                return match.group(0)

            source_relative_path = (source_file.parent / path).resolve()
            project_relative_path = (Path(project_path) / path).resolve()
            resolved_path = next(
                (candidate for candidate in (source_relative_path, project_relative_path) if candidate.is_file()),
                None,
            )
            if resolved_path is None:
                return match.group(0)
            return f"{match.group(1)}{resolved_path}{match.group(1)}"

        rewritten_content = path_pattern.sub(make_absolute, content)
        destination_file.write_text(rewritten_content, encoding="utf-8")