import logging
logger = logging.getLogger(__name__)

from .NmlSwitchWriter import NmlSwitchWriter
from .NmlSpritesetWriter import NmlSpritesetWriter


class NmlVariantWriter:
    def __init__(self, variant):

        self.variant = variant
        self.switch_writer = NmlSwitchWriter()
        self.spriteset_writer = NmlSpritesetWriter()

        self.filepath = variant.vehicle.folder_path + "/" + variant.nml_filename

        

    def write(self):        
        variant = self.variant

        with open(self.filepath, 'w') as f:
            f.write("// !!!!! Warning, auto generated file. Do not edit this file. !!!!!\n")
            f.write("// .gnml files are auto-generated from the accompanying .yaml file.\n")
            f.write("// Do not edit this file, it will be over-written during the next build.\n")
            f.write("")


            # if getattr(variant.sprite_handler, "purchase_sprite", None) is not None:
            #     self.spriteset_writer.write_spriteset(f, variant.sprite_handler.purchase_sprite, variant)

            # for sprite in variant.sprite_handler.spritesets:
            #     # Only write each spriteset once
            #     if not any(s.name == sprite.name for s in self.written_spritesets):
            #         self.spriteset_writer.write_spriteset(f, sprite, variant)
            #         self.written_spritesets.append(sprite)

            # for switch in variant.switches + variant.sprite_handler.switches:
            #     self.switch_writer.write_switch(
            #         f,
            #         switch["vehicle_type"],
            #         switch["target_type"],
            #         switch["name"] if switch["name"].lower().startswith("sw_") else f"sw_{switch['name']}",
            #         switch["expression"],
            #         switch["values"]
            #     )

            self.write_item(f, variant)

    def write_item(self, f, variant):
        # TODO Implement writing the main item block for the variant
        pass