import pathlib


class StringWriter:
    def __init__(self, registry, lang_folder="Lang"):
        self.registry = registry
        self.lang_folder = pathlib.Path(lang_folder)
        self.file_path = self.lang_folder / "english.lng"

    def write_file(self):
        self.lang_folder.mkdir(parents=True, exist_ok=True)

        with open(self.file_path, "w", encoding="utf-8") as f:
            f.write("##grflangid 0x01\n")
            f.write("# AUTOGENERATED FILE, DO NOT MODIFY THIS FILE DIRECTLY\n\n")

            for key, value in self.registry.items():
                f.write(f"{key:<40}:{value}\n")