import time
import logging
from pathlib import Path

from Badge import BadgeRegistry
from Lang.StringRegistry import _registry
from Lang.StringWriter import StringWriter
from NmlWriter import NmlGrfWriter, NmlVariantWriter, NmlCollator, NmlCompiler
from Project import Project
from Sprites.PalettedImage import PalettedImage
from Templates.SpritesheetLegacyConverter import SpritesheetLegacyConverter
from Templates.TemplateLoaderNML import TemplateLoaderNML
from Vehicle import VariantIterator, VehicleSpriteAllocator
from YamlHandler import VehicleLoader, GrfLoader
from .BuildContext import BuildContext
from .CandidateFinder import CandidateFinder

logger = logging.getLogger(__name__)


class Builder:

    def __init__(self):
        self.nmlCollator = NmlCollator()
        self.nmlCompiler = NmlCompiler()
        return

    def build(self, project_data, log_nml_output=False):
        # Clear global registries so each project build starts fresh
        _registry.clear()
        BadgeRegistry().clear()
        context = BuildContext(project_data=project_data, log_nml_output=log_nml_output)

        stages = [
            self._load_project,
            self._validate_project_path,
            self._load_grf,
            self._load_palette,
            self._write_templates,
            self._discover_candidates,
            self._process_candidates,
            self._collate_nml,
            self._write_language,
            self._compile_newgrf,
            self._copy_newgrf,
        ]

        start_time = time.time()
        for stage in stages:
            try:
                stage(context)
            except Exception as exc:
                logger.exception(f"Build stage {stage.__name__} failed: {exc}")
                return

        elapsed = round(time.time() - start_time, 2)
        logger.info(f"BRBuild build process for project '{context.project.name}' completed successfully.")
        logger.info(f"Successful variants: {len(context.successful_variants)}. Failed variants: {len(context.failed_variants)}.")
        logger.info(f"BRBuild project '{context.project.name}' build complete after {elapsed} seconds.")

    def _load_project(self, ctx: BuildContext):
        if isinstance(ctx.project_data, Project):
            logger.debug(f"Received project data is already a Project instance: {ctx.project_data}")
            ctx.project = ctx.project_data
        else:
            logger.debug(f"Received project data is not a Project instance, attempting to create one: {ctx.project_data}")
            ctx.project = Project(ctx.project_data)

        ctx.nml_output_folder = f"WorkingData/{ctx.project.name}/"
        ctx.lang_folder = str(Path(ctx.nml_output_folder) / "lang")

        if not ctx.project.build:
            raise RuntimeError(f"Skipping project '{ctx.project.name}' because build is disabled.")

        logger.info(f"BRBuild is attempting to build project '{ctx.project.name}' in {ctx.project.path}.")

    def _validate_project_path(self, ctx: BuildContext):
        if not ctx.project.path.is_dir():
            raise FileNotFoundError(f"Project folder '{ctx.project.path}' does not exist.")

    def _load_grf(self, ctx: BuildContext):
        loader = GrfLoader(ctx.project.path / ctx.project.grfFolder / "GRF.yaml")
        grf = loader.load()
        writer = NmlGrfWriter(grf)
        ctx.nml_files.append(writer.write_grf_gnml(ctx.nml_output_folder + "GRF.gnml"))

    def _load_palette(self, ctx: BuildContext):
        ctx.palette = PalettedImage.load_palette(ctx.project.palette)
        logger.debug(f"Loaded palette from {ctx.project.palette}")

    def _write_templates(self, ctx: BuildContext):
        """Pre-write the project's (or BRBuild's default) NML template blocks.

        These must be collated before any vehicle candidates, since vehicles reference
        `tmpl_*` templates by name in their generated spriteset() blocks.
        """
        template_dir = self._resolve_template_folder(ctx)
        if template_dir is None:
            logger.debug("No template folder found; skipping template pre-write.")
            return

        template_files = sorted(template_dir.glob("*.pnml"))
        if not template_files:
            logger.debug(f"No .pnml template files found in '{template_dir}'.")
            return

        output_path = Path(ctx.nml_output_folder) / "Templates.gnml"
        output_path.parent.mkdir(parents=True, exist_ok=True)

        with open(output_path, "w", encoding="utf-8") as out:
            out.write("// !!!!! Warning, auto generated file. Do not edit this file. !!!!!\n")
            out.write("// Collated NML `template` definitions, written before any vehicle candidates.\n")
            for template_file in template_files:
                out.write(f"\n\n// File: {template_file}\n")
                out.write(template_file.read_text(encoding="utf-8"))

        ctx.nml_files.append(str(output_path))
        logger.info(f"Pre-wrote {len(template_files)} template file(s) from '{template_dir}' to {output_path}")

    def _resolve_template_folder(self, ctx: BuildContext) -> Path | None:
        if ctx.project.templateFolder:
            candidate = ctx.project.path / ctx.project.templateFolder
            if candidate.is_dir():
                return candidate
            logger.warning(f"Configured template_folder '{candidate}' does not exist; falling back to BRBuild's default templates.")

        default_dir = Path(__file__).resolve().parent.parent / "Templates"
        return default_dir if default_dir.is_dir() else None

    def _get_template_definitions(self, ctx: BuildContext) -> list:
        """Load (and cache) the project's or BRBuild's default NML template definitions."""
        if ctx.template_definitions is None:
            template_dir = self._resolve_template_folder(ctx)
            ctx.template_definitions = TemplateLoaderNML().read_folder(str(template_dir)) if template_dir else []

        return ctx.template_definitions

    def _discover_candidates(self, ctx: BuildContext):
        if ctx.project.targetFolders:
            logger.debug(f"Scanning specified target folders for candidates: {ctx.project.targetFolders}")
            scan_paths = [ctx.project.path / target for target in ctx.project.targetFolders]
        else:
            logger.debug("No target folders specified; scanning project root.")
            scan_paths = [ctx.project.path]

        ctx.candidates = self.find_candidates(scan_paths)
        if len(ctx.candidates) == 0:
            raise RuntimeError(f"No candidates found for project '{ctx.project.name}'. Halting build process.")

        elapsed_candidates = len(ctx.candidates)
        logger.info(f"Candidate finding complete. Found {elapsed_candidates} candidates.")

    def find_candidates(self, scan_paths):
        candidates = []
        for scan_path in scan_paths:
            if not scan_path.exists():
                logger.warning(f"Target folder '{scan_path}' does not exist; skipping.")
                continue
            if not scan_path.is_dir():
                logger.warning(f"Target path '{scan_path}' is not a directory; skipping.")
                continue

            logger.debug(f"Finding candidates in folder: {scan_path}")

            finder = CandidateFinder(scan_path)
            found = finder.find_candidates()
            candidates.extend(found)

        logger.info(f"Found {len(candidates)} candidates.")
        return candidates

    def _process_candidates(self, ctx: BuildContext):
        if not ctx.candidates:
            raise RuntimeError("No candidates found")

        for candidate in ctx.candidates:
            self._process_candidate(candidate, ctx)

        if len(ctx.successful_variants) == 0:
            raise RuntimeError(f"No successful variants were generated for project '{ctx.project.name}'. Halting build process.")

    def _process_candidate(self, candidate, ctx: BuildContext):
        logger.info(f"Processing candidate: {candidate.get('name')}")

        for pnml in candidate.get("pnml_files", []):
            logger.debug(f"\tFound manual PNML file: {pnml}")
            ctx.nml_files.append(pnml)

        for file in candidate.get("files", []):
            logger.debug(f"\tParsing YAML file: {file}")
            vehicle = VehicleLoader.load(file)
            logger.debug(
                f"\tLoaded vehicle: {vehicle.name} with identifier {vehicle.identifier}, "
                f"{len(vehicle.profiles)} profiles, and {len(vehicle.liveries)} liveries."
            )

            has_spritesheet = bool(vehicle.spritesheet_path) and Path(vehicle.spritesheet_path).is_file()
            allocator = None

            if has_spritesheet:
                allocator = self._load_sprite_allocator(vehicle, ctx)
                if allocator is None:
                    logger.error(
                        f"Skipping vehicle '{vehicle.identifier}': unable to confidently identify spritesets "
                        f"in '{vehicle.spritesheet_path}'."
                    )
                    ctx.failed_variants.append(f"{vehicle.identifier} (spritesheet)")
                    continue

            for variant in VariantIterator(vehicle):
                logger.debug(
                    f"\tGenerated variant: {variant.vehicle.name}, using livery {variant.livery.name} "
                    f"and profile {variant.profile.identifier}"
                )

                if allocator is not None:
                    try:
                        variant.spritesets, variant.sprite_template_names, variant.sprite_lengths = allocator.get(
                            variant.profile, variant.livery
                        )
                        purchase = allocator.get_purchase()
                        variant.purchase_spriteset, variant.purchase_template_name = purchase if purchase else (None, None)
                    except Exception as exc:
                        logger.exception(f"Unable to assign sprites for variant {variant}: {exc}")
                        ctx.failed_variants.append(repr(variant))
                        return

                try:
                    variant.process()
                except Exception as exc:
                    logger.exception(f"Error processing variant {variant}: {exc}")
                    ctx.failed_variants.append(repr(variant))
                    return

                try:
                    variant_writer = NmlVariantWriter(variant, ctx.nml_output_folder)
                    nml_file = variant_writer.write()
                    ctx.nml_files.append(nml_file)
                except Exception as exc:
                    logger.exception(f"Unable to write NML for variant {variant}: {exc}")
                    ctx.failed_variants.append(repr(variant))
                    return

                ctx.successful_variants.append(variant)

    def _load_sprite_allocator(self, vehicle, ctx: BuildContext):
        """Build a sprite allocator for a vehicle's spritesheet.

        Returns None if the sheet can't be confidently classified against the known
        templates - the caller treats that as a fatal error for this vehicle.
        """
        self._convert_spritesheet(vehicle, ctx)

        try:
            return VehicleSpriteAllocator(vehicle, ctx.palette, self._get_template_definitions(ctx))
        except Exception as exc:
            logger.exception(f"Unable to load spritesheet for vehicle '{vehicle.identifier}': {exc}")
            return None

    def _convert_spritesheet(self, vehicle, ctx: BuildContext):
        """Normalise a vehicle's spritesheet in place to only its recognised template rows."""
        definitions = self._get_template_definitions(ctx)
        if not definitions:
            logger.debug(f"No template definitions found; skipping spritesheet conversion for '{vehicle.identifier}'.")
            return

        v_type = vehicle.vehicle_type
        v_type_str = v_type.name.lower() if hasattr(v_type, "name") else str(v_type).lower()

        try:
            converter = SpritesheetLegacyConverter(definitions, ctx.palette)
            kept = converter.process(vehicle.spritesheet_path, v_type_str)
            logger.info(f"Converted spritesheet for '{vehicle.identifier}': kept {len(kept)} recognised row(s).")
        except Exception as exc:
            logger.exception(f"Unable to convert spritesheet for vehicle '{vehicle.identifier}': {exc}")

    def _collate_nml(self, ctx: BuildContext):
        if len(ctx.nml_files) == 0:
            raise RuntimeError("No NML files available for collation.")

        ctx.nml_filepath = self.nmlCollator.collate(ctx.nml_files, ctx.project.name)
        logger.info(f"NML collation complete: {ctx.nml_filepath}")

    def _write_language(self, ctx: BuildContext):
        ctx.lang_folder = str(Path(ctx.nml_output_folder) / "lang")
        string_writer = StringWriter(_registry, ctx.lang_folder)
        string_writer.write_file()
        logger.info(f"Wrote language file to {ctx.lang_folder}")

    def _compile_newgrf(self, ctx: BuildContext):
        if not ctx.nml_filepath:
            raise RuntimeError("NML file path is missing for compilation.")

        ctx.newgrf_filepath = self.nmlCompiler.compile(ctx.nml_filepath, ctx.lang_folder, ctx.log_nml_output)
        logger.info(f"newGRF compilation complete: {ctx.newgrf_filepath}")

    def _copy_newgrf(self, ctx: BuildContext):
        if not getattr(ctx, 'newgrf_filepath', None):
            raise RuntimeError("Compiled GRF path is missing for copying.")

        self.nmlCompiler.copy_newgrf(ctx.newgrf_filepath)
        logger.info(f"newGRF copying complete for {ctx.newgrf_filepath}")
